# Generated by Django 2.1.8 on 2019-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twice',
            name='brith',
            field=models.DateTimeField(),
        ),
    ]
