# Generated by Django 2.1.8 on 2019-05-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiceapp', '0002_auto_20190524_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
            ],
        ),
    ]
